/*=======================================
 * Created by Atsushi Umakatsu on 27.12.2018.
 /=======================================*/

/*jslint node: true */
"use strict";

var sanitize = require("./sanitize");


/*==================================================
 * Takes the JSON file, generated by the license-checker from
 * and puts its contents into a html table
 /==================================================*/

function createPList(json, grunt) {

  var output =
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>PreferenceSpecifiers</key>
    <array>`;

  /*
   * Get the name of every top node inside the json.
   * In this case, the node name is the name of the package, that we are currently looking at.
   */
  const packageNames = Object.getOwnPropertyNames(json);

  const packageList = [];
  packageNames.forEach(function(packageName) {
    const splitPackage = packageName.split("@");
    let name;
    if(packageName.indexOf("@")===0){
      name ="@" + splitPackage[1];
    }else{
      name =splitPackage[0];
    }

    if(packageList.includes(name)){
      return;
    }
    packageList.push(name);

    const repository = sanitize.parsePlist(json[packageName].repository);
    const repositoryText = repository ? "|- repository: "+ repository : "";
    const publisher = sanitize.parsePlist(json[packageName].publisher);
    const publisherText = publisher ? "|- publisher: "+ publisher : "";
    const licenses = sanitize.parsePlist(json[packageName].licenses);
    if (licenses) {
      output += `
        <dict>
          <key>Title</key>
          <string>${name}</string>
          <key>Type</key>
          <string>PSGroupSpecifier</string>
          <key>FooterText</key>
          <string>|- licenses: ${licenses}
${repositoryText}
${publisherText}</string>
        </dict>`;
    }
  });

  if (grunt.config.data["grunt-license-report"].output.font) {
    output += `
        <dict>
        <key> Title </key>
        <string> Google;
      Noto;
      Fonts </string>
      <key> Type </key>
      <string > PSGroupSpecifier </string>
      <key > FooterText </key>
      <string> https;
    ://ja.osdn.net/projects/opensource/wiki/SIL_Open_Font_License_1.1</string>
    </dict>`;;
    }

    output += `
    </array>
    <key>Title</key>
    <string>Licenses</string>
    <key>StringsTable</key>
    <string>Licenses</string>
  </dict>
</plist>`;

    return output;
  }


  exports.createPList = createPList;
